development:
  adapter: postgresql
  database: screen_scrape_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: screen_scrape_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: screen_scrape_production
  pool: 5
  timeout: 5000
